name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

 login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Server
    run: docker build ./server filmclubwts2020/server:latest
    - name: Build Client
    run: docker build ./client filmclubwts2020/front:latest
    - name: Build Nginx
    run: docker build ./nginx  filmclubwts2020/nginx:latest
    -name: Docker Push
    run:
    docker push filmclubwts2020/server:latest
    docker push filmclubwts2020/front:latest
    docker push filmclubwts2020/nginx:latest
    
    
