name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

 docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push server
        uses: docker/build-push-action@v3
        with:
          context: ./server
          push: true
          tags: filmclubwts2020/server:latest
      -
       name: Build and push client
        uses: docker/build-push-action@v3
        with:
          context: ./client
          push: true
          tags: filmclubwts2020/client:latest
          
      -
       name: Build and push nginx
          uses: docker/build-push-action@v3
          with:
            context: ./nginx
            push: true
            tags: filmclubwts2020/nginx:latest
      
        
    
    
    
